# Generated by Django 4.1.5 on 2023-01-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Твои хард скиллы', max_length=255, verbose_name='новый навык')),
            ],
        ),
    ]
